language: java
jdk: oraclejdk11
#sudo: false
install: true

addons:
  sonarcloud:
    organization: "subhas-dev"
    token:
      secure: 441802eb558a1046f23a532f67d00867d145fa4d
    #token: ${{ secrets.SONAR_TOKEN }}
    
script:
 # Instruction
 # - ./gradlew sonarqube
 ./gradlew clean check jacocoTestReport sonarqube build
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'
